In [29]:
from numpy import *
a=array([[4,16,5,21,7],[28,9,38,13,51],[17,67,22,40,30],[20,40,10,3,13],[21,34,48,29,26]])
print(a)

[[ 4 16  5 21  7]
 [28  9 38 13 51]
 [17 67 22 40 30]
 [20 40 10  3 13]
 [21 34 48 29 26]]


In [30]:
totalsum=0
row=zeros(a.shape[0])
col=zeros(a.shape[1])

print (row)
print (col)


[ 0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.]


In [31]:
for i in range (a.shape[0]):
    for j in range (a.shape[1]):
        totalsum=totalsum+a[i][j]
        row[i]=row[i]+a[i][j]
        col[j]=col[j]+a[i][j]
print(totalsum)
print(row)
print(col)

612
[  53.  139.  176.   86.  158.]
[  90.  166.  123.  106.  127.]
